import ProductItem from "../product-item/product-item";
import "./product-list.css";

const products = [
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQjkWvw85voKEiOfR9ngPw8W5yRzM_knHNWasY12A4PJrrlRbGm45GoqKpn4w&usqp=CAE",
	"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT7t9us9jJGqkY4LbcfVg-SjN2uOXd2PxMJBBQC8bJBF5h7jL3RNgN1TWhGnn96gdxtrbKygPo&usqp=CAE",
	"https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRI47Isb0RGacSZy3e4fAfxVeIHv-yAY7aISh96HBBwZlPvXPB6ELsOKyMWvzA&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ2X-jTvA13-4wFvHrOskAph_GrIQKExNE3L-6S-HSbVMH1KtM1bh39rHXAUBP0DOeesRvpfOIb&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ3uMQgal28Rb3DHSnY57PNKYbis_ONxLD7Iqr6iyVk_rYnvx85va7PYHTK&usqp=CAE",
	"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcStOpzNds4eByHO-wBLUDfvA_fEf3iuPBAGn55g-oMpMfo9bjoA1mgZO-6-dhIa_T61WfpM_Rnw&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS0UksnjMyKz2Brh_DxTfSnre-C5pP5SYdO1gKJj6IM27qO3YArMb2HBMzeHc-jgaTV9EOTaqY&usqp=CAE",
	"https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSsFkAZd0SJSipMoAvpNMLJr9y5OS8fBt3nGAtexehkShX1Stl5DiIElB7UzA&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcToSuEGgFQPNjUa8qf1IORTHrZIAkaPocxAAvEbkcDtb5oYq8FsvIQEIArA&usqp=CAE",
	"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ7KcwIfnphKVoUczmXfxsx-mKUTolN7nGAkIqwWWUjS6gpFWmUO9orAHBispcAkqojkdvJtBQ&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRKhBXGWFvTyDEfO80jP3l9Rp5Y0np3Z1amq2DmMBtw1DG3MHgOEoOaWcVYyMOszeSHK5NKEg&usqp=CAE",
	"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSqRRwBoesHJExBInyHUJA9fF39ToVxyOdjTZGRXOtbQaLGy4aosENgzyO5ryY&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTccZi3iNiLRiborloQmbarvrFJoTFq828SU3BfX3cPxUHbC-iBgZzLJ1u1pA&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ9zTHl8Om8BHhMAhWb6kf66MTH9GEE7MuU1Mksr8Q4hZ9FmqxaoC1RKB-Z&usqp=CAE",
	"https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSOOjLsFI2mqjvpangdG9ObKfzx0Z2vlNeUB8URAiBtb5ghSZjbdsy_aoIj3j5OYVoZqQUk3fU&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQBchqwR7RjCCvts0ShTHzzgBy9fO51lxjpsKzZFG0uFUZkVcHATL0ZvhVj&usqp=CAE",
	"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSY54l6bSkMVa_wSYCxRoQoX9SM51x--qMsCcxJoho85ewUjv29Lx4h7J5RPw&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT9QvCfIbGcsFptfQWItXtF4EhMZZjFOcoIcr1kh8kaFsjlnBKgrS6Zrs3cf8l_w_nxsHoaFH-j&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRHBok9DQhc_MK-wysEA3rk6oBwSqFMc5S2W-DCCAEqg1WG9fInpanhxTMXNQ&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTiNzNOIpBaAMcEKOu6xRbQBXjrhEBo84hur88Z3UaIBItos8JsjlTOJJb1Ze-fcQd68tjQLA8&usqp=CAE",
	"https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcT2jGp33-RYcYAweHp9Plsp3777pjbLnn8WkozPYoM3IcpcWvM2QnwNgGYY3g&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQX2eIsBqXUz-PpD8Bq68Uq0NdssE-e_tvFApfq6oI78LUQpXeCCA4UDCnDmw&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRoNDX9DBwARCzva2yNvMkegKI2X6VstjAsLML4XgnO-UpwHuhicXoKgFrlNExZ2N9S6ZR3EQ&usqp=CAE",
	"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ40j4_F2ObqkOiRpSf6-BuwPIR2YLNRkoegxeY0xXXfR2knFa5VP3mXWo3pMbxJnfcgSbfkg&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTkkOhVQ1yQAVw7-PmDqJG1CwKmylYhXiKQ_dNRlmuEnZPOp1C8LK_6prLQXw&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR6s7pUThpGXozwD-sau1H_-jTqxqWhT1TleqUqrEx-mZuHq6ZsxUehBK_O&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQAdRecRLJIz-HsiiP6MHwcJ5VU6TdXKfBFmiop884UR_zp11Ii4nW5DKlDT_soaJkaosadsTM&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ-pqigOsIcLpP2v46RRKLU7RRIFrlB20QHIl_UE_dhMkFVmBePXxJtqQxmAg&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcREtVXwChxrsCSdx7-vT7kejidfo5-dlxHwNtFVV_KV21SSrl9TheLguwCoVrm4N5VBiQ_CxhEC&usqp=CAE",
	"https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRrdS5x7LBLS-ns2tCcfDvlzEQGZTQMDMPvNCzfINa67LP7r9NPgPm4DdSdsw&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSMojn6U1Vzjhuw0ihq22u6-GxES_Jz4cSsEk5eoAnxSmFGMM9q972ZJVIwfCVyuwsG9Xa1qNA&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTDmIdkwyr2gDs1uFpM2Fd-t6s-RTU4eSwH8UG7HttHm95wTWQZ8JfpGyyqro-U4TIIxUzO4oEf&usqp=CAE",
	"https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRP6mfS77tDTV6N8sQDzwvxgJzj_FsLTrqzShyj_BJZqMEVwmULSoKjTr8mnw&usqp=CAE",
	"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSPb2RTgmig9qbzz_jnNtZP6DLJbDjhXqe9GHxdl1CsXal_hvAgkkCMY2Fj-A&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRVqVmH3Vwme5nWNSb567ViHLAg98RS9LekgDoATWX4o8ukTBhSZzGpZ2GX&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSRFIaVrA0svUBng_jqbGx-ONnzP2SWNTSf5Zm6LOtYMcnSl5leVHwS1E1IYMw&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQEiTFYpA7re95RIzPPkYyi9EaO2_-K8KHNdP-L0MLI053NNhGJXaqvMXPnAN6ft11OGFb4NEheLso&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR_vcZy-fG_-wcixZBtJiOr-rsgqxVx5W-DfVRXlgulVkCoq-riMzH4HaPhgHAJdSU9qBOIkMk&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQwyavP14EpAcV8gF-YAvtiD4H9A8Gc3SB9k6fnsdSxgWQyRAm9UVe4cO4OKhHRZ-6_9yv4rozS&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSKusGo6ImzbGY8yZtQxnXPaP0snWQPPynPhtZdfahmQw7pDhqhpZul8pThqFUGuxJ_5mme-Wk&usqp=CAE",
	"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNHB4IiBoZWlnaHQ9IjI0cHgiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0iI2ZmZiI+PHBhdGggZD0iTTE5IDYuNDFMMTcuNTkgNSAxMiAxMC41OSA2LjQxIDUgNSA2LjQxIDEwLjU5IDEyIDUgMTcuNTkgNi40MSAxOSAxMiAxMy40MSAxNy41OSAxOSAxOSAxNy41OSAxMy40MSAxMnoiLz48cGF0aCBkPSJNMCAwaDI0djI0SDB6IiBmaWxsPSJub25lIi8+PC9zdmc+Cg==",
	"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSgnRmn5x8d9b9iyJoc5O--YlGD3gLtB5A1Z8ZUYbrJs3xd94GgsqbS0t1YsRWfXleOBZ6i&usqp=CAE",
	"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRLtN2r7NfhvspSfB_JArNkcgc9Bgrs8H5nWNZwg_XN6CMngKBkXQ_PHJEAd7U0uJYh4848rg&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRJFGhWq2yuIuu4vpbSOo1AKXmKSnYwCKqgknIo94FpeZryD09Cx3L1ofy0&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS_e2hpH9CiaAMUPacFKkj3bEBfWMV3KXDiJnH5_EN1loNvzP3vdso9tNw&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRqGDMcQr1pskd3biIX0d6CRD3EieSVD2nyfovzYFyxbsKwlravarCexnQ4P8LlUpbkzOhmtw&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQOAvgeIbcRB3VprqdXRy_0CIKjCTCsZhFVgmaIH19ezdUVgCBVtHmKguA3-dxQESUcGbh2uw&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRKU9BgylhbkBw3q-6ATAPZNMrUEX0F-E7T34RR9aG6xAToXK1gaaZaAo5d&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSbYp8Aq38_aWYdTiUshFvs1gEg6i5wItCOMv3486flvcRO0bafi2mfpHidg8f4t7zyMbIT&usqp=CAE",
	"https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRqu_SyMHyqOqbCfsaiqxVCnvt8fByhIUPloVFKDg7rCgPjMgW0TnA7bDqF&usqp=CAE",
	"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQCkUfWS9Z7CPypSMFeV4A3FjiL4_RqFi5JyEaSokS2maiT_zehweRKihlWe6O6dyTOGImUmA&usqp=CAE",
	"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSdwjQHbBfWAMch_QO72v2tE-lvEzgZf-piy50fpRJ65jtyXGZysf_90q57qu6tKn4VT2Rb&usqp=CAE",
	"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT3m3neaHkizj4Y8Aq-yMco7hGNXTQl5ZIcQ1Db7MlZ11-gOsG80ASekpkx&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTdyoEPX5JbXOoyAV5qpr2AMTH9CMLcNtOTOG9T3XBOpYzxgzv1Rw8HhGv0tBTOxfpZHJq7qQ&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS1VDPiotpg1swlav6_ryS2tZmP8m0jlt4LVh_CqFjgJ1Og-7MA7T3E-EM&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRoRW6dxwdb8xKPlKp6wjTbBqRD3yojeWemFvw7vN9LqTVSTAK5jsJdlGmh57HMltc-BhH36A&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSEpNgutgLMHO09135ZN5EV8eLVPbFoZhzrId6tw291YJ9zMwOBVm0AZHcFc2qOAT4SX74PXw&usqp=CAE",
	"https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTtJOh76DBmf8PgMQAOGXlcdvChEijJpeYe46p4SbsJpwpTIoqcFairK-WmaffLo_RCpRZ0NQ&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTEULhKwSg8uiy4NOioKD5lcx76nkflBkohUPWXIeM2TyvxBGXwW4VJliCfqn0N52nmCAhsTA&usqp=CAE",
	"https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ6YMpwhD_6jMatE2bWezffpOlaZcumJ1JweJ1XxTDMOSLWywCLjbNEbU9wW3m48BgWfCs5&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRpqYD7yKYbi9YJlZK84nWjTT6fFzSw3GnpD953SF8wV1ea4RlbljjTtvL1OkkfuRt_GyvH&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTen6uOGm69BvxAbT2-we8pVjsg-wS5PkFejz1JkIz7GZjsYoR0mza4OfGGhJ30vS5q3aPhIA&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcS7Ww3XQ3SOEZBz_YGVHKC7CWxRPZ1E3qzEe66b1Jsd_h4LQw6FbjTcfzoyF2n94XTw2gsXow&usqp=CAE",
	"https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRRNCk27n-QG_eVe0Qx3_SfBIoLsmZtX1Hx18x49zieaisHE3Ik7X-LygB8&usqp=CAE",
	"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSjTVNLw6ZNJ_77JpwFc-jzfTXLY1OEKgrnqguJ4o4wNwzKyTlxrZHJXhGB&usqp=CAE",
	"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTZUFuRdYSRNjIc0OIzTMKma8sYZ1j4CqmotrV6-hvtLoJyjpWdWvwVCv0&usqp=CAE",
];
const ProductList = () => {
	const productList = products.map((ele) => {
		return <ProductItem name="product" price="$300" imageUrl={ele} />;
	});
	return <div className="product-list-container">{productList}</div>;
};

export default ProductList;
